version: "3.9"

volumes:
  transaction-api_data:

services:
  transaction-app:
    build: ./
    command: ./app
    ports:
      - "8587:8587"
    volumes:
      - .:/src
    environment:
      - GONOSUMDB=off
      - TZ=Asia/Almaty
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13.2-alpine
    volumes:
      - transaction-api_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5436:5432

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
